### ISSUE TITLE
make API call to get data for frontend visualisation

### ISSUE THREAD

**Issue by CraneOfTheWild** [high-mood/PSE#27]
the api should get called using a userid which returns data in the form of:

username : String
number of songs in this datarequest : Int
mean-excitedness : Int
mean-happiness : Int
Array of songs: with for each song: {
songname : String
timestamp : Int
excitednes : Int
happiness : Int
}

**Comment by Diallo** [comment]
WIP

**Comment by Diallo** [comment]
I'm going to assume the username you are referring to is "display_name" https://developer.spotify.com/documentation/web-api/reference/users-profile/get-current-users-profile/

@CraneOfTheWild

**Comment by CraneOfTheWild** [comment]
@Diallo 
Yes the display_name is needed to display personalized messages with an appropriate name.

**Comment by Diallo** [comment]
Done
