### ISSUE TITLE
Song recommendation api data

### ISSUE THREAD

**Issue by SkylarGeeta** [high-mood/PSE#33]
Spotify recommendation:
- [ ] Function needs (max) 5 most recent song ID
- [ ] Function needs oauth token
- [ ] Possibly all parameters from top 5 songs, maybe not needed

**Comment by Diallo** [comment]
Please be more specific

What format?  See example format
![image](https://user-images.githubusercontent.com/33268295/59469321-ca00bb80-8e34-11e9-94b3-40856f62700f.png)

Please be more descriptive.
