### ISSUE TITLE
Add responsive text and styling to charts to personalize the website

### ISSUE THREAD

**Issue by CraneOfTheWild** [high-mood/PSE#38]
To personalize the website we can add text to each graph/chart to explain what it means.
These can be personalized with the persons name and be responsive to what kind of data is being shown.
For example: in the radarchart we see that most songs have high positivity and exitedness and this is reflected in the text.

**Comment by CraneOfTheWild** [comment]
graphs should be displayed alternating oon the left and right with text on the other side.
if the view is too narrow the graph will go on top and description below

titles should always be on the top

**Comment by Diallo** [comment]
Was this completed @HNegus @CraneOfTheWild ?

**Comment by Diallo** [comment]
No reply and  #75 is more recent and contains this functionality.
