### ISSUE TITLE
Create method to update mood analysis algorithm based on reviews

### ISSUE THREAD

**Issue by BarrydeVries** [high-mood/PSE#44]
User reviews of song moods should be saved in a database and used to retrain the mood analysis algorithm.

**Comment by Jonasvdham** [comment]
- [ ] Design an interface for the website where users can leave their feedback
- [ ] Design a function to compare the user feedback with our estimate (to filter troll responses)
- [x] Append data received from feedback to dataset
- [x] Retrain the ML-model on the updated dataset with a set interval
