### ISSUE TITLE
User feedback for retraining ML-model

### ISSUE THREAD

**Issue by Jonasvdham** [high-mood/PSE#62]
- [x] add user-feedback on a track mood to the database. 
    - [x] Add response_excitedness, response_happiness, responses_count to Songmood
    - [x] API post responses

- [ ] update get_moods to take responses into account.

- [x] add the trainingset for the ML-model to the DB.
    - [x] add tracks in PSE-Backend/moodanalysis/machinelearning/analyzed_tracks_1.csv with 20 responses). in Songmood

**Comment by Diallo** [comment]
I've done my part in this functionality, rest remains to be done or should have already been done. @Jonasvdham please reopen if required.
