### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by reijne** [high-mood/PSE#74]
- [x] Update Metric API - based on # songs
    - [x]  add Songmood - excitedness, happiness

- [x] Update Mood API - based on timeframe
For a given timeframe look in the entire history of a user, then return the average excitedness, happiness, and all other metrics per hour
    - [x] change influxdb database to songs
    - [x] add metrics and moods to songids

- [x] add API for metrics & mood based on days/dates
return the average excitedness, happiness and all other metrics per day

**Comment by Diallo** [comment]
Done
